### PR TITLE
Updating README to be more explicit about the return value of the fun…

### PR DESCRIPTION
**Pull request by GoogilyBoogily**
…ctions and updated the CHANGELOG accordingly.

### CODE REVIEW

**Comment by fidian** [comment]
I'm approving this pull request. Did you intentionally decide that newer changes in the changelog should be at the bottom or did you just put them there without considering how this will appear in 10 years of maintenance?

**Review by fidian — APPROVED** [review]

**Comment by fidian** [comment]
Oh sorry, your CHANGELOG.md is not following the style guide and needs another blank line above the date heading you've added.

**Review by fidian — CHANGES_REQUESTED** [review]
Newline above your "1.0.1 - 2017-02-22" heading to match style guide.

**Comment by GoogilyBoogily** [comment]
I instinctively went with how the Shelf and Gisnep changelogs worked. Will update.

**Review by fidian — APPROVED** [review]

**Pull request merged**
